### ISSUE TITLE
input shape

### ISSUE THREAD

**Issue by zhangkai07** [duttapallabi2907/U-VixLSTM#1]
data = torch.randn(2, 1, 30, 256, 256).cuda()
    model = UVixLSTM(class_num=2, img_dim=128, in_channels=1, ).cuda()

    output = model(data)
    print(output.shape)
    
When I use the above code to input, the model error, please ask, what is the shape of the model input?

**Comment by duttapallabi2907** [comment]
The model input would be:
data = torch.randn(4, 1, 96, 96, 96).cuda()
model = UVixLSTM(class_num=2, img_dim=96, in_channels=1 ).cuda()

output = model(data)
print(output.shape)
